on: push

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew build --scan

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew build --scan

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew build --scan
